name: Mon Premier Workflow
on: workflow_dispatch
jobs:
  premierJob:
    runs-on: ubuntu-latest
    steps:
      - name: Mon premier job
        run: echo "Démarrage du jobs"
      - name: Mes premières instructions
        run: ls /
      - name: Fin du premer Job
        run: echo "That's all Folks"
    
# workflow_dispatch indique que le workflow pourra être déclenché manuellement depuis GitHub.
